services:
  - type: web
    name: suspicious-profile-analyzer-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python main.py
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.11.0